### ISSUE TITLE
Typos in text

### ISSUE THREAD

**Issue by jonaszmclaren** [SoftwareEngineeringProjectCEIE/DevelopmentMethodology#1]
Hi Arek,

please correct the following things in the Development Methodology document:

2. 
     2. Designers
     3. Programmers
4.  built-in
     To access it
5. 
    1. Every two weeks (no "For")
    4. Each commit requires
    4. ... by at least
6. In "Changes history" I would extend the table, because when there will be some changes available, in the "Description" column there is going to be a lot of text.

Best regards,
Jonasz

**Comment by gabr** [comment]
About 4.
The size of the columns will change automatically based on they content.
I can force fixed column width but in my opinion it is not necessary.

**Comment by jonaszmclaren** [comment]
If it will change, it is ok, force is not needed:)

**Comment by jonaszmclaren** [comment]
Typos 2. and 3. iii were not corrected.
