### ISSUE TITLE
Errors within Development Methodology

### ISSUE THREAD

**Issue by kkoscielniak** [SoftwareEngineeringProjectCEIE/DevelopmentMethodology#2]
3) "Git version control system hosted on GitHub is used" - not sure if this statement is grammatically correct. Could you check this one?
4) "built-in", instead of  "build in"
5.3) "people", instead of "persons"

// cc: @przezor @tomasz-buchta @jonaszmclaren @szpaqq

**Comment by gabr** [comment]
About 4 I agree, my bad, will be corrected in next commit.
In my opinion 3 is correct as well as 5.3
So we need extra opinion.

/cc @SoftwareEngineeringProjectCEIE/all

**Comment by jonaszmclaren** [comment]
5.3: "persons" is totally fine for me.

**Comment by szpaqq** [comment]
Ye i feel like persons seems legit, we can always use teammates or smth
15 paź 2015 21:50 "jonaszmclaren" <notifications@github.com> napisał(a):

**Comment by przezor** [comment]
3) That point is a little bit overcomplicated when it comes to the structure of a sentence, however it is easily understandable. I would leave it as it is.

**Comment by przezor** [comment]
5.3: 

In modern English, people is the de facto plural of person. People and person have separate Latin origins, and they came to English at different times by different paths, but there are examples of people used as a plural of person from as early as the 14th century. Persons was the original plural, and it is possible to find examples of its use in all types of writing up to the present, but it prevails only in a few contexts, most notably law and law enforcement, and in a few common phrases (e.g., persons of interest, displaced persons, missing persons). Elsewhere, it usually gives way to people.

CONCLUSION: modern English = people, but grammatically both are correct :)

**Comment by jonaszmclaren** [comment]
Peoples? Are you kidding me? :)

**Comment by gabr** [comment]
X____x thx
