### ISSUE TITLE
Feedback 1 - project title

### ISSUE THREAD

**Issue by gabr** [SoftwareEngineeringProjectCEIE/DevelopmentMethodology#3]
> Project title may be helpful

But there is a project title on the title page.

So, maybe some change in style or order?

/cc @SoftwareEngineeringProjectCEIE/all

**Comment by przezor** [comment]
My proposition:
<h3> SystemSoftware Engineering </h3>
<h2> Parameter Management System </h2>
<strong> Development Methodology </strong>
