### ISSUE TITLE
Feedback 2 - project roles

### ISSUE THREAD

**Issue by gabr** [SoftwareEngineeringProjectCEIE/DevelopmentMethodology#4]
>it may be worthwhile to differentiate within the programmers and testers - is someone managing these tasks? Which tester is going to test what and who is deciding?

Three points here:
 1. Differentiate within the programmers and testers
 2. Who is managing tester/programmer tasks
 3. Who is deciding which tester is testing what

Discuss and vote here on those points.

/cc @SoftwareEngineeringProjectCEIE/all

**Comment by przezor** [comment]
My proposition: If person x did a task, then person x assigns someone to review it.

**Comment by przezor** [comment]
1. We differentiated... 2.3 - programmers & 2.6 - test

**Comment by przezor** [comment]
2. If a part of code was prepared, reviewed and accepted, then testers are informed about that fact and they begin their work.
