### ISSUE TITLE
Feedback 3 - bug tracking system

### ISSUE THREAD

**Issue by gabr** [SoftwareEngineeringProjectCEIE/DevelopmentMethodology#5]
> How are you planning to design the issue (task / bug) flow?

Any idea for some kind of "flow"?

/cc @SoftwareEngineeringProjectCEIE/all

**Comment by przezor** [comment]
Open -> In progress -> To review -> Done :D

**Comment by kkoscielniak** [comment]
Jira-like :P

W dniu poniedziałek, 26 października 2015 Luke <notifications@github.com>
napisał(a):

**Comment by przezor** [comment]
Exactly like in JIRA :D Oczywiście z "to review" idzie do "open" jak jest odrzucone.

**Comment by gabr** [comment]
Ok, but how exactly this will look in practice?

**Comment by przezor** [comment]
@gabr What do you mean? Are you asking about a tool or flow itself?

**Comment by gabr** [comment]
@przezor 
The flow is clear for me.
Question was about the way to manage this this flow, the tools i.e.

**Comment by kkoscielniak** [comment]
We can use Github labels for the beginning. Each issue can be labeled, as far as I know there's a way to filter issues by label. 

Or if you know any free tool which allows us to do the same, I'm open for discussion.

**Comment by gabr** [comment]
I don't know, that's why I'm asking.
IMO the labels are a good idea.

**Comment by przezor** [comment]
I think that labels are good idea for the beginning.
