### ISSUE TITLE
Feedback 4 - methodology - summary

### ISSUE THREAD

**Issue by gabr** [SoftwareEngineeringProjectCEIE/DevelopmentMethodology#6]
> who is going to prepare the summary?

In my opinion the team leader, but I'm open for other suggestions.

/cc @SoftwareEngineeringProjectCEIE/all

**Comment by przezor** [comment]
Team leader + each team member gives a short summary what he has done (sth like daily scrum meeting)

**Comment by kkoscielniak** [comment]
Sounds like a plan

W dniu poniedziałek, 26 października 2015 Luke <notifications@github.com>
napisał(a):

**Comment by przezor** [comment]
Propozycja: next meetin w tygodniu od 2 listopada. Miejsce: uczelnia / skype
??????
