### ISSUE TITLE
Feedback 6 - methodology - documentation

### ISSUE THREAD

**Issue by gabr** [SoftwareEngineeringProjectCEIE/DevelopmentMethodology#8]
> more attention should be given to delegating the responsibility - everyone should know what they are expected to do. General statements like 'are informed' or 'will be done' expose the risk that noone would feel responsible for that.

This is about 5.5

Team leader in my opinion, but this is a larger topic connected with previous Methodology statements.
Any suggestions are welcomed.

/cc @SoftwareEngineeringProjectCEIE/all

**Comment by przezor** [comment]
My propostion: Project leader is responsible for delegating the responsibility. During planning, we assign tasks to certain people.
